Portafolio/Pages/Contacto.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Portafolio.Pages
{
    public class ContactoModel : PageModel
    {
        public void OnGet()
        {
        }

        public void OnPost()
        {

        }

        public void OnGetDescargarCv()
        {

        }
    }
}

Portafolio/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Portafolio.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Portafolio/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Portafolio.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Portafolio/Pages/Contacto.cshtml
@page
@model Portafolio.Pages.ContactoModel
@{
}

<form method="post" class="mb-5 mr-5 ml-5 mt-2 pr-5 pl-5 pb-5 pt-2">

    <div class="row m-4">
        <div class="col">
            <h1 class="mb-3">Contacto</h1>
            <input class="input-nombre" type="text" placeholder="Nombre" />
        </div>

    </div>
    <div class="row m-4">
        <div class="col">
            <textarea class="textarea-asunto" cols="40" rows="6" placeholder="Asunto"></textarea>
        </div>
    </div>
    <div class="row m-4">
        <div class="col">
            <input class="input-submit" type="submit" />
        </div>
    </div>

    <div class="row m-4">
        <div class="col">
            <a class="text-black-50" asp-page-handler="DescargarCv">Descargar CV</a>
        </div>
    </div>

</form>

Portafolio/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}


<div class="presentacioncard row shadow-lg p-3 rounded-lg m-3">
    <div class="presentacionimg col-4"><img src="~/img/perfil.jpg" class="imgperfil" /></div>
    <div class="presentaciontext col-8">
    
        <hr class="hrdetalle" />
        lorm
    
    
    </div>
</div>


<div class="tecnologias row shadow-lg p-3 rounded-lg m-3">
    <div class="presentecnologias col-12">lorm</div>
</div>


<div id="proyectos"></div>

Portafolio/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Portafolio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3 p-2">
            <div class="container">
                <a class="navbar-brand text-black" asp-area="" asp-page="/Index">Alfredo Sánchez - Desarrollador .Net</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Contacto">Contacto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark text-muted">
        <div class="container text-white">
            &copy; 2022 - Alfredo Sánchez - <a asp-area="" asp-page="/Contacto">Contáctame</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>